spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.116.78.196:3307/zijianmall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  thymeleaf:
    cache: false


  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#    alicloud:
#      access-key: LTAI4G5ko4QenH2hGAUFmSMq
#      secret-key: U4np9B0IDwhip3LG2a5NgnV1jbapPJ
#      oss:
#        endpoint: oss-cn-shanghai-internal.aliyuncs.com

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 0
      logic-not-delete-value: 1

server:
  port: 9000

logging:
  level:
    com.zijianmall.product: debug
